name: z_chat
description: A chat App for Zeroplus Mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/z_chat.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

